[build]
  functions = "netlify/functions"
  publish = "phongluyenviet" 

[functions]
  node_bundler = "esbuild"

# Quy tắc chuyển hướng để URL gốc (/) hiển thị nội dung của index.html
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200