[build]
  functions = "netlify/functions"
  publish = "phongluyenviet" 

[functions]
  node_bundler = "esbuild"

# Quy tắc chuyển hướng mới: Trỏ URL gốc đến file chat.html
[[redirects]]
  from = "/"
  to = "/chat.html"  # <-- Đã đổi tên index.html thành chat.html
  status = 200