[build]
  functions = "netlify/functions"
  publish = "phongluyenviet" 

[functions]
  node_bundler = "esbuild"

# Quy tắc chuyển hướng để trang chủ (/) trỏ đến trang chat.html
[[redirects]]
  from = "/"
  to = "/chat.html"
  status = 200